.\"=========================================
.\" "Cane Pofuente" command for Linux Shell. 
.\" Inspired by "sl" command of  mtoyoda / sl. 
.\" All right reserved to mtoyoda.
.\"
.\" Alteration by Rombo
.\"=========================================

.TH SL 1 "August 1, 2022"
.SH NAME
cane \- A funny command for Linux Shell.
.SH SYNOPSIS
.B cane
[
.B \-F
]
.SH DESCRIPTION
.B cane
"Cane Pofuente" command for Linux Shell, inspired by sl command of  mtoyoda / sl (All right reserved to him).
.PP
.TP
.B \-F
It flies like a DogCopter.
.PP
.SH AUTHOR
Rombo